### ISSUE TITLE
Replace DRAW AGAIN button with SKIP and ABSENT

### ISSUE THREAD

**Issue by prondzyn** [TorunJUG/Xenia#7]
Current DRAW AGAIN button allows to skip person when he/she is absent and he/she is removed from further draws these day. We need to handle situation when the person already have item which he/she won and he/she does not want it but would like to take part in another's items draws.

TODO:
- rename button DRAW AGAIN to ABSENT and keep current functionality
- add SKIP button which draws again without removing the person from further draws

The perfect solution for SKIP button would be:
1. do not remove the person from other items draw and
2. remove the person from current item draw

**Comment by sawickil** [comment]
huh, I thought xenia worked in that way :) what a surprise. Good idea!

**Comment by sawickil** [comment]
I'm trying with this one ;) PR soon

**Comment by sawickil** [comment]
done, please review
